on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        FEATURE: [default, simd, blas]
    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies for blas
        if: matrix.FEATURE == 'blas'
        run: sudo apt install -y libopenblas-dev pkg-config
      - name: Build binaries in "${{ matrix.FEATURE }}" mode
        run: cargo build -F ${{ matrix.FEATURE }}
      - name: Run tests in "${{ matrix.FEATURE }}" mode
        run: cargo test -F ${{ matrix.FEATURE }}


  # publish:
  #   needs: test
  #   if: github.ref == 'refs/heads/release'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v6
  #     - name: Login into crates.io
  #       run: cargo login ${{ secrets.CRATES_IO }}
  #     - name: Build binaries in "release" mode
  #       run: cargo build -r
  #     - name: "Package for crates.io"
  #       run: cargo package # verification step before publishing
  #     - name: "Publish to crates.io"
  #       run: cargo publish