on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        FEATURE: [default, simd, blas]
    steps:
      - uses: actions/checkout@v6
      - name: Build binaries in "${{ matrix.FEATURE }}" mode
        run: cargo build --profile ${{ matrix.FEATURE }}
      - name: Run tests in "${{ matrix.FEATURE }}" mode
        run: cargo test --profile ${{ matrix.FEATURE }}
